/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package consultas;

import java.awt.Color;
import basedatos.Conexion;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author CSjes
 */
public class ConsultasClientes extends javax.swing.JFrame {

    /**
     * Creates new form ConsultasClientes
     */
    public ConsultasClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        jpBarraCerrar = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        btnSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jtApellidos = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jtDirección = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jtColonia = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jtCP = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jtCiudad = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jtEstado = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jtTelefono = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jbBuscar = new javax.swing.JButton();
        jbRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(585, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpFondo.setBackground(new java.awt.Color(227, 95, 30));
        jpFondo.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        jpBarraCerrar.setBackground(new java.awt.Color(227, 95, 30));

        btnExit.setBackground(new java.awt.Color(227, 95, 30));

        btnSalir.setBackground(new java.awt.Color(227, 95, 30));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setText("X");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpBarraCerrarLayout = new javax.swing.GroupLayout(jpBarraCerrar);
        jpBarraCerrar.setLayout(jpBarraCerrarLayout);
        jpBarraCerrarLayout.setHorizontalGroup(
            jpBarraCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBarraCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpBarraCerrarLayout.setVerticalGroup(
            jpBarraCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBarraCerrarLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("Clientes");

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        jtNombre.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jtNombre.setForeground(new java.awt.Color(204, 204, 204));
        jtNombre.setText("Ingrese su nombre");
        jtNombre.setBorder(null);
        jtNombre.setOpaque(false);
        jtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtNombreMousePressed(evt);
            }
        });
        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(252, 195, 20));
        jSeparator1.setForeground(new java.awt.Color(252, 195, 20));

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos:");

        jtApellidos.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jtApellidos.setForeground(new java.awt.Color(204, 204, 204));
        jtApellidos.setText("Ingrese sus apellidos");
        jtApellidos.setBorder(null);
        jtApellidos.setOpaque(false);
        jtApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtApellidosMousePressed(evt);
            }
        });
        jtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApellidosActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(252, 195, 20));
        jSeparator2.setForeground(new java.awt.Color(252, 195, 20));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel4.setText("Dirección:");

        jtDirección.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jtDirección.setForeground(new java.awt.Color(204, 204, 204));
        jtDirección.setText("Ingrese su dirección");
        jtDirección.setBorder(null);
        jtDirección.setOpaque(false);
        jtDirección.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtDirecciónMousePressed(evt);
            }
        });
        jtDirección.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDirecciónActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(252, 195, 20));
        jSeparator3.setForeground(new java.awt.Color(252, 195, 20));

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel5.setText("Colonia:");

        jtColonia.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jtColonia.setForeground(new java.awt.Color(204, 204, 204));
        jtColonia.setText("Ingrese su colonia");
        jtColonia.setBorder(null);
        jtColonia.setOpaque(false);
        jtColonia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtColoniaMousePressed(evt);
            }
        });
        jtColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtColoniaActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(252, 195, 20));
        jSeparator4.setForeground(new java.awt.Color(252, 195, 20));

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel10.setText("C.P:");

        jtCP.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jtCP.setForeground(new java.awt.Color(204, 204, 204));
        jtCP.setText("Ingrese su codigo postal");
        jtCP.setBorder(null);
        jtCP.setOpaque(false);
        jtCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtCPMousePressed(evt);
            }
        });
        jtCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCPActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(252, 195, 20));
        jSeparator5.setForeground(new java.awt.Color(252, 195, 20));

        jLabel11.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel11.setText("Ciudad:");

        jtCiudad.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jtCiudad.setForeground(new java.awt.Color(204, 204, 204));
        jtCiudad.setText("Ingrese su ciudad");
        jtCiudad.setBorder(null);
        jtCiudad.setOpaque(false);
        jtCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtCiudadMousePressed(evt);
            }
        });
        jtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCiudadActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(252, 195, 20));
        jSeparator6.setForeground(new java.awt.Color(252, 195, 20));

        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel12.setText("Estado:");

        jtEstado.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jtEstado.setForeground(new java.awt.Color(204, 204, 204));
        jtEstado.setText("Ingrese su estado");
        jtEstado.setBorder(null);
        jtEstado.setOpaque(false);
        jtEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtEstadoMousePressed(evt);
            }
        });
        jtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEstadoActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(252, 195, 20));
        jSeparator7.setForeground(new java.awt.Color(252, 195, 20));

        jLabel13.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel13.setText("Telefono:");

        jtTelefono.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jtTelefono.setForeground(new java.awt.Color(204, 204, 204));
        jtTelefono.setText("Ingrese su telefono");
        jtTelefono.setBorder(null);
        jtTelefono.setOpaque(false);
        jtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtTelefonoMousePressed(evt);
            }
        });
        jtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTelefonoActionPerformed(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(252, 195, 20));
        jSeparator8.setForeground(new java.awt.Color(252, 195, 20));

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel6.setText("Buscar:");

        jtID.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jtID.setForeground(new java.awt.Color(204, 204, 204));
        jtID.setText("Ingrese el ID del cliente");
        jtID.setBorder(null);
        jtID.setOpaque(false);
        jtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtIDMousePressed(evt);
            }
        });
        jtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIDActionPerformed(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(252, 195, 20));
        jSeparator9.setForeground(new java.awt.Color(252, 195, 20));

        jbBuscar.setBackground(new java.awt.Color(2, 159, 220));
        jbBuscar.setText("Buscar Cliente");
        jbBuscar.setBorderPainted(false);
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbRegistrar.setBackground(new java.awt.Color(2, 159, 220));
        jbRegistrar.setText("Registrar Cliente");
        jbRegistrar.setBorderPainted(false);
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBarraCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtColonia, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(jSeparator4)))
                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                                .addComponent(jSeparator1)))
                                        .addGroup(jpFondoLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtDirección, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator8)
                                    .addComponent(jtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtEstado))
                                    .addComponent(jLabel11)
                                    .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpFondoLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jtCP)
                                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                    .addComponent(jLabel1)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtID, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(jSeparator9))
                        .addGap(47, 47, 47)
                        .addComponent(jbBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbRegistrar)
                .addGap(206, 206, 206))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addComponent(jpBarraCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbBuscar))
                .addGap(36, 36, 36)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtDirección, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(jtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addComponent(jbRegistrar)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(jpFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnExit.setBackground(new Color(252, 195, 20));
        btnSalir.setForeground(Color.black);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnExit.setBackground(new Color(227, 95, 30));
        btnSalir.setForeground(Color.white);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtApellidosActionPerformed

    private void jtDirecciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDirecciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDirecciónActionPerformed

    private void jtColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtColoniaActionPerformed

    private void jtCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCPActionPerformed

    private void jtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCiudadActionPerformed

    private void jtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEstadoActionPerformed

    private void jtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelefonoActionPerformed

    private void jtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIDActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        Conexion conn = Conexion.getInstance();
        PreparedStatement ps;
        ResultSet rs = null;
        String consultaSQL = "SELECT nom, ape, dir, col, cp, cid, est, tel FROM Cliente WHERE id=?";
        try {
            conn.Conectar();
            ps = conn.cadena.prepareStatement(consultaSQL);
            if (!jtID.getText().equals("Ingrese el ID del cliente")) {
                try {
                    ps.setInt(1, Integer.parseInt(jtID.getText()));
                    rs = ps.executeQuery();
                    if (rs.next()) {
                        jtNombre.setText(rs.getString(1));
                        jtApellidos.setText(rs.getString(2));
                        jtDirección.setText(rs.getString(3));
                        jtColonia.setText(rs.getString(4));
                        jtCP.setText(rs.getString(5));
                        jtCiudad.setText(rs.getString(6));
                        jtEstado.setText(rs.getString(7));
                        jtTelefono.setText(rs.getString(8));
                    } else {
                        JOptionPane.showMessageDialog(null, "No se econtro el cliente");
                    }
                    rs.close();
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Ingrese un numero valido");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un numero de cliente");
            }
            ps.close();
            conn.Desconectar();
            conn.cadena.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            ps = null;
            conn = null;
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        Conexion conn = Conexion.getInstance();
        PreparedStatement ps;
        String consultaSQL = "INSERT INTO Cliente(nom, ape, dir, col, cp, cid, est, tel)\n"
                + "VALUES(?,?,?,?,?,?,?,?) ;";
        try {
            conn.Conectar();
            ps = conn.cadena.prepareStatement(consultaSQL);
            ps.setString(1, jtNombre.getText().trim());
            ps.setString(2, jtApellidos.getText().trim());
            ps.setString(3, jtDirección.getText().trim());
            ps.setString(4, jtColonia.getText().trim());
            ps.setString(5, jtCP.getText().trim());
            ps.setString(6, jtCiudad.getText().trim());
            ps.setString(7, jtEstado.getText().trim());
            ps.setString(8, jtTelefono.getText().trim());
            ps.execute();
            ps.close();
            conn.Desconectar();
            conn.cadena.close();
            JOptionPane.showMessageDialog(null, "Cliente: " + jtNombre.getText() + " registrado(a)");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            ps = null;
            conn = null;
        }
        jtNombre.setText("Ingrese su nombre");
        jtApellidos.setText("Ingrese sus apellidos");
        jtDirección.setText("Ingrese su dirección");
        jtColonia.setText("Ingrese su colonia");
        jtCP.setText("Ingrese su codigo postal");
        jtCiudad.setText("Ingrese su ciudasd");
        jtEstado.setText("Ingrese su estado");
        jtTelefono.setText("Ingrese su telefono");
        jtNombre.setForeground(new Color(204, 204, 204));
        jtApellidos.setForeground(new Color(204, 204, 204));
        jtDirección.setForeground(new Color(204, 204, 204));
        jtColonia.setForeground(new Color(204, 204, 204));
        jtCP.setForeground(new Color(204, 204, 204));;
        jtCiudad.setForeground(new Color(204, 204, 204));
        jtEstado.setForeground(new Color(204, 204, 204));
        jtTelefono.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jtIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtIDMousePressed
        if (jtID.getText().equals("Ingrese el ID del cliente")) {
            jtID.setText("");
            jtID.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtIDMousePressed

    private void jtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtNombreMousePressed
        if (jtNombre.getText().equals("Ingrese su nombre")) {
            jtNombre.setText("");
            jtNombre.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtNombreMousePressed

    private void jtApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtApellidosMousePressed
        if (jtApellidos.getText().equals("Ingrese sus apellidos")) {
            jtApellidos.setText("");
            jtApellidos.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtApellidosMousePressed

    private void jtDirecciónMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDirecciónMousePressed
        if (jtDirección.getText().equals("Ingrese su dirección")) {
            jtDirección.setText("");
            jtDirección.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtDirecciónMousePressed

    private void jtColoniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtColoniaMousePressed
        if (jtColonia.getText().equals("Ingrese su colonia")) {
            jtColonia.setText("");
            jtColonia.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtColoniaMousePressed

    private void jtCPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCPMousePressed
        if (jtCP.getText().equals("Ingrese su codigo postal")) {
            jtCP.setText("");
            jtCP.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtCPMousePressed

    private void jtCiudadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCiudadMousePressed
        if (jtCiudad.getText().equals("Ingrese su ciudad")) {
            jtCiudad.setText("");
            jtCiudad.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtCiudadMousePressed

    private void jtEstadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEstadoMousePressed
        if (jtEstado.getText().equals("Ingrese su estado")) {
            jtEstado.setText("");
            jtEstado.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtEstadoMousePressed

    private void jtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTelefonoMousePressed
        if (jtTelefono.getText().equals("Ingrese su telefono")) {
            jtTelefono.setText("");
            jtTelefono.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtTelefonoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultasClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnExit;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JPanel jpBarraCerrar;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JTextField jtApellidos;
    private javax.swing.JTextField jtCP;
    private javax.swing.JTextField jtCiudad;
    private javax.swing.JTextField jtColonia;
    private javax.swing.JTextField jtDirección;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables
}
